config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'users#index'

  resources :users, only: %i[index new create destroy] do
    resources :notifications
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :user

  validates :time, :date, :title, :description, presence: true

  scope :not_sent, -> { where(sended: false) }
  scope :at_present_time, -> { where('date = :today AND time = :now', today: Date.current, now: Time.now.strftime('%k:%M')) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  has_many :notifications, dependent: :destroy
  validates :first_name, :middle_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to :root
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :initialize_notification, only: %i[show edit update destroy]
  before_action :initialize_user

  def index
    @notifications = @user.notifications.order(sended: :asc)
  end

  def show; end

  def new
    @notification = Notification.new
  end

  def edit
    redirect_to user_notifications_url(@user) if @notification.sended?
  end

  def create
    @notification = @user.notifications.create(notification_params)
    if @notification.save
      redirect_to user_notifications_url(@user)
    else
      render :new
    end
  end

  def update
    if @notification.update(notification_params)
      redirect_to user_notifications_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @notification.destroy
    redirect_to user_notifications_url(@user)
  end

  private

  def initialize_user
    @user = User.find(params[:user_id])
  end

  def initialize_notification
    @notification = Notification.find(params[:id])
  end

  def notification_params
    params.require(:notification).permit(:title, :description, :date, :time)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :initialize_user, only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def initialize_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :middle_name, :email)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminPanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true, url: user_notifications_path) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control my-2'%>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_field :time%>
  </div>


  <div class="actions">
    <%= form.submit 'Create Notification', class: 'btn btn-success my-2' %>
  </div>
  <%= link_to 'Back', user_notifications_path %>
<% end %>

app/views/notifications/edit.html.erb
<div class='container my-lg-4'>
  <div class='row'>
    <div class='col-sm-12 text-center'>
      <div class='col-sm-8 text-left'>
        <h1>Editing Notification</h1>
        <%= form_with(model: @notification, local: true,  url: user_notification_path(@user)) do |form| %>
          <% if @notification.errors.any? %>
            <div id="error_explanation">
              <ul>
              <% @notification.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control my-2' %>
          </div>

          <div class="field">
            <%= form.label :description %>
            <%= form.text_area :description, class: 'form-control my-2' %>
          </div>

          <div class="field">
            <%= form.label :date %>
            <%= form.date_select :date, class: 'form-control my-2' %>
          </div>

          <div class="field">
            <%= form.label :time %>
            <%= form.time_field :time %>
          </div>


          <div class="actions">
            <%= form.submit 'Edit Notification', class: 'btn btn-success my-2' %>
          </div>
        <% end %>


        <%= link_to 'Show', user_notification_path(@notification) %> |
        <%= link_to 'Back', user_notifications_path %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<div class='container my-lg-4'>
  <div class='row'>
    <div class='col-sm-12 text-center'>
     <h1 class='text-dark'>Notifications for: <%= @user.email %></h1> 
      <% if @notifications.present? %>
        <table class='table'>
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Date</th>
              <th>Time</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @notifications.each do |notification| %>
              <tr>
                <td><%= notification.title %></td>
                <td><%= truncate(notification.description, length: 50) %></td>
                <td><%= notification.date %></td>
                <td><%= I18n.l(notification.time, format: :short_format) %></td>
                <td><%= link_to 'Show', user_notification_url(@user.id, notification), class: 'btn btn-outline-info' %></td>
                <% if notification.sended? %>
                  <td><em>Sended</em></td>
                <% else %>
                  <td><%= link_to 'Edit', edit_user_notification_path(@user.id, notification), class: 'btn btn-outline-success' %></td>
                <% end %>
                <td><%= link_to 'Destroy', user_notification_path(@user.id, notification), class: 'btn btn-outline-dark', method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p><em> Please, add first notification </em></p>
      <% end %>
      <%= link_to 'Back to users', root_path, class: 'btn btn-secondary btn-lg'%>
      <%= link_to 'Add Notification', new_user_notification_path, class: 'btn btn-lg btn-primary'%>
    </div>
  </div>
</div>      
<br>

app/views/notifications/new.html.erb
<div class='container my-lg-4'>
  <div class='row'>
    <div class='col-sm-12 text-center'>
      <div class='col-sm-8 text-left'>
      <h1>New Notification</h1>
      <%= render 'form', notification: @notification %>
    </div>
    </div>
  </div>
</div>

app/views/notifications/show.html.erb
<div class='container my-lg-4'>
  <div class="row pb-3">  
    <div class="col-md-auto col-xs-text-center"> 
      <p class='text-left'>
        <strong>Title:</strong>
        <%= @notification.title %>
      </p>

      <p class='text-left'>
        <strong>Description:</strong>
        <%= @notification.description %>
      </p>

      <p class='text-left'>
        <strong>Date to send:</strong>
        <%= @notification.date %>
      </p>

      <p class='text-left'>
        <strong>Time to send:</strong>
        <%= I18n.l(@notification.time, format: :short_format)  %>
      </p>

      <%= link_to 'Back', user_notifications_path %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, class: 'form-control my-2' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control my-2' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create User', class: 'btn btn-success my-2' %>
  </div>

  <%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<div class='container my-lg-4'>
  <div class='row'>
    <div class='col-sm-12 text-center'>
      <h1 class='text-dark'>Users List</h1>
      <% if @users.present? %>
        <table class='table'>
          <thead>
            <tr>
              <th>Last name</th>
              <th>First name</th>
              <th>Middle name</th>
              <th>Email</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.last_name %></td>
                <td><%= user.first_name %></td>
                <td><%= user.middle_name %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'Notification List', user_notifications_path(user.id), class: 'btn btn-outline-info' %></td>
                <td><%= link_to 'Destroy', user, class: 'btn btn-outline-dark', method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p><em> Please, add first user </em></p>
        <% end %>
      <br>
      <%= link_to 'New User', new_user_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='container my-lg-4'>
  <div class='row'>
    <div class='col-sm-12 text-center'>
      <div class='col-sm-8 text-left'>
        <h1>New User</h1>
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>